apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: insight-hub
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: backend
  
  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: insight-hub-backend:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: insight-hub-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: insight-hub-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: insight-hub-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: insight-hub-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insight-hub-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: insight-hub-secret
                  key: JWT_SECRET

            - name: CLIENT_URL
              value: "http://65.0.187.44"
