apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insight-hub

resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - ingress.yml
  - mysql/deployment.yaml
  - mysql/service.yml
  - mysql/pvc.yml
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - monitoring/backend-servicemonitor.yaml

images:
  - name: insight-hub-backend
    newName: mofarhankhann/insight-hub-backend
    newTag: "18"

  - name: insight-hub-frontend
    newName: mofarhankhann/insight-hub-frontend
    newTag: "18"
