apiVersion: v1
kind: Secret
metadata:
  name: insight-hub-secret
  namespace: insight-hub
type: Opaque
stringData:
  DB_USER: insightuser
  DB_PASSWORD: Insight@123
  MYSQL_ROOT_PASSWORD: Root@123
  JWT_SECRET: 8xIL2jbiiirbiin3s9xRLI4yD1hzKRlEr0Xu23JVzNA
